const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("exchangeDesktop", {
  loadConfig: () => ipcRenderer.invoke("config:load"),
  saveConfig: (content: string) => ipcRenderer.invoke("config:save", content),
  configPath: () => ipcRenderer.invoke("config:path"),
  listProviders: () => ipcRenderer.invoke("providers:list"),
  testProvider: (p: { provider: string; apiKey: string; baseUrl?: string }) => ipcRenderer.invoke("providers:test", p),
  startMcp: () => ipcRenderer.invoke("mcp:start"),
  stopMcp: () => ipcRenderer.invoke("mcp:stop"),
  runDoctor: (opts: { endpoint?: string; insecure?: boolean }) => ipcRenderer.invoke("doctor:run", opts),
  askExchange: (payload: { prompt: string; conversationId?: string; confirmed?: boolean; tool?: string; args?: any; formPatch?: Record<string, unknown>; systemPrompt?: string }) => ipcRenderer.invoke("exchange:ask", payload),
  oplogList: () => ipcRenderer.invoke("oplog:list"),
  oplogClear: () => ipcRenderer.invoke("oplog:clear"),
  onOpLog: (cb: (entry: any) => void) => ipcRenderer.on("oplog:append", (_e: any, entry: any) => cb(entry)),
  isMcpRunning: () => ipcRenderer.invoke("mcp:isRunning"),
  getBackendInfo: () => ipcRenderer.invoke("backend:info"),
  updaterCheck: () => ipcRenderer.invoke("updater:check"),
  updaterUpdate: () => ipcRenderer.invoke("updater:update"),
  updaterRestart: () => ipcRenderer.invoke("updater:restart"),
  promptValidate: (prompt: string) => ipcRenderer.invoke("prompt:validate", { prompt }),
  promptEnhance: (prompt: string, useModel?: boolean) => ipcRenderer.invoke("prompt:enhance", { prompt, useModel }),
  applockStatus: () => ipcRenderer.invoke("applock:status"),
  applockEnrollStart: (label?: string) => ipcRenderer.invoke("applock:enroll-start", { label }),
  applockEnrollVerify: (token: string, pin?: string) => ipcRenderer.invoke("applock:enroll-verify", { token, pin }),
  applockUnlock: (code: string, pin?: string) => ipcRenderer.invoke("applock:unlock", { code, pin }),
  applockDisable: (code: string) => ipcRenderer.invoke("applock:disable", { code }),
  applockRecoveryRegenerate: (code: string) => ipcRenderer.invoke("applock:recovery-regenerate", { code }),
});
