// Sample prompts per MCP tool, shown in the Docs tab as clickable "Try"
// chips (they fill the prompt box; nothing auto-runs). Pure + testable.
// Rule for contributors: every tool registered in src/tools/* MUST have at
// least one entry here — tests/toolExamples.test.ts enforces it, so a new
// tool without a sample fails CI. Keep samples routable where the keyword
// router supports the phrasing (spot-checked in tests); otherwise use the
// clearest natural phrasing (AI mode resolves the rest).

export const TOOL_EXAMPLE_PROMPTS: Record<string, string[]> = {
  "ai.analyze_mailbox": ["Analyze alice@contoso.com"],
  "ai.anomaly_detection": ["Anomaly detection"],
  "ai.capacity_forecast": ["Predict when my databases will fill up"],
  "ai.change_impact_report": ["What happens if I move 500 mailboxes from DB01 to DB05?"],
  "ai.cleanup_recommendation": ["Cleanup recommendations to recover space"],
  "ai.comparative_report": ["Compare production vs DR"],
  "ai.compromised_account_detection": ["Compromised accounts"],
  "ai.configuration_risk": ["Config hardening risks"],
  "ai.daily_report": ["Daily exchange report"],
  "ai.exchange_executive_summary": ["Executive summary"],
  "ai.incident_report": ["Create an incident report for delayed mail"],
  "ai.mail_flow_intelligence": ["Analyze mail flow intelligence"],
  "ai.mailbox_cleanup_advisor": ["Cleanup advisor for alice@contoso.com"],
  "ai.management_report": ["Management report"],
  "ai.migration_advisor": ["Migration readiness assessment"],
  "ai.migration_eta": ["Migration ETA and progress"],
  "ai.migration_prioritization": ["Migration batch prioritization"],
  "ai.ndr_intelligence": ["Analyze today's NDRs"],
  "ai.permission_risk_report": ["Permission risk report"],
  "ai.ask_exchange": ["Show me all mailboxes over 50 GB"],
  "ai.root_cause_analysis": ["Root cause of delayed mail"],
  "ai.security_risk_report": ["Security risk report"],
  "ai.tell_me_everything": ["Tell me everything about admin@contoso.com"],
  "ai.things_you_should_know": ["Things i should know"],
  "ai.what_if_analysis": ["What if disk space runs out on EXCH01?"],
  "certificate.enable_services": ["Enable IIS and SMTP services for a certificate"],
  "certificate.get_expiring": ["Certificates expiring soon"],
  "clientaccess.get_autodiscover_info": ["Autodiscover for contoso.com"],
  "clientaccess.get_virtual_directories": ["Show virtual directories"],
  "clientaccess.test_owa": ["Test OWA connectivity"],
  "contact.list": ["List contacts"],
  "dag.get_info": ["Show DAG info"],
  "dag.get_witness_status": ["Check DAG witness status"],
  "dag.list": ["Show DAGs"],
  "dag.set_activation_policy": ["Set activation policy for database copy"],
  "dag.simulate_failover_check": ["Simulate a failover check"],
  "database.add_copy": ["Add database copy of DB01 on EXCH02"],
  "database.dismount": ["Dismount database DB01"],
  "database.get_backup_status": ["Check database backup status"],
  "database.get_copy_status": ["Show database copy status"],
  "database.get_whitespace_and_growth": ["Database whitespace and growth"],
  "database.list": ["List databases"],
  "database.mount": ["Mount database DB01"],
  "database.move_active": ["Failover database DB01"],
  "database.new_repair_request": ["Repair database DB01"],
  "database.remove_copy": ["Remove database copy of DB01 on EXCH02"],
  "database.resume_copy": ["Resume copy of DB01"],
  "database.suspend_copy": ["Suspend copy of DB01"],
  "diagnostics.test_exchange_search": ["Check content index health"],
  "exchange_connect_mailbox": ["Reconnect disconnected mailbox"],
  "exchange_create_calendar_event": ["Create a calendar event"],
  "exchange_create_mailbox": ["Create mailbox"],
  "exchange_delete_message": ["Delete a message"],
  "exchange_disable_mailbox": ["Disable mailbox alice@contoso.com"],
  "exchange_discover_mailboxes": ["How many mailboxes in DB01"],
  "exchange_enable_mailbox": ["Enable mailbox for new user"],
  "exchange_forward_message": ["Forward a message"],
  "exchange_get_archive_status": ["Check archive status for alice@contoso.com"],
  "exchange_get_availability": ["Get availability for alice@contoso.com"],
  "exchange_get_cas_mailbox": ["Client access for alice@contoso.com"],
  "exchange_get_dag": ["Get DAG details"],
  "exchange_get_database_copy_status": ["Check database copy status"],
  "exchange_get_distribution_group_member": ["Show members of Sales Team"],
  "exchange_get_exchange_certificate": ["Certificates expiring soon"],
  "exchange_get_health_report": ["Full health report"],
  "exchange_get_inbox_rules": ["Show inbox rules for alice@contoso.com"],
  "exchange_get_inplace_hold": ["Check In-Place holds"],
  "exchange_get_journal_rule": ["Journal rules"],
  "exchange_get_litigation_hold": ["Check litigation hold for alice@contoso.com"],
  "exchange_get_mailbox": ["Get mailbox alice@contoso.com"],
  "exchange_get_mailbox_database": ["Show mailbox database DB01"],
  "exchange_get_mailbox_folder_permission": ["Show calendar sharing for alice@contoso.com"],
  "exchange_get_mailbox_import_request": ["Import request status"],
  "exchange_get_mailbox_import_request_statistics": ["Show import progress details"],
  "exchange_get_mailbox_junk_config": ["Check junk mail settings for alice@contoso.com"],
  "exchange_get_mailbox_permission": ["Show raw mailbox permissions for alice@contoso.com"],
  "exchange_get_mailbox_permissions": ["Permissions of alice@contoso.com"],
  "exchange_get_mailbox_quota": ["Quota for alice@contoso.com"],
  "exchange_get_mailbox_restore_request": ["Restore request status"],
  "exchange_get_mailbox_statistics": ["Mailbox statistics for alice@contoso.com"],
  "exchange_get_message": ["Show message details"],
  "exchange_get_message_tracking_log": ["Search message tracking logs"],
  "exchange_get_mobile_device": ["Mobile devices for alice@contoso.com"],
  "exchange_get_monitoring_item": ["Show monitoring items"],
  "exchange_get_oof": ["OOF status"],
  "exchange_get_ps_trace": ["Show PowerShell trace"],
  "exchange_get_public_folder": ["Show public folders"],
  "exchange_get_queue": ["Show delayed queues"],
  "exchange_get_queue_digest": ["Show queue digest"],
  "exchange_get_retention_policy": ["Show retention policies"],
  "exchange_get_retention_policy_tag": ["List retention policy tags"],
  "exchange_get_role_groups": ["Role groups"],
  "exchange_get_server": ["Show server EXCH01"],
  "exchange_get_server_component_state": ["Check server component states"],
  "exchange_get_server_health": ["Check managed availability health"],
  "exchange_get_softdeleted_mailbox": ["Soft-deleted mailboxes"],
  "exchange_get_transport_config": ["Show transport configuration"],
  "exchange_get_transport_rules": ["Show transport rules"],
  "exchange_get_transport_service": ["Show transport service settings"],
  "exchange_get_virtual_directory": ["List virtual directories"],
  "exchange_list_accepted_domains": ["List accepted domains"],
  "exchange_list_calendar_events": ["List calendar events"],
  "exchange_list_contacts": ["List contacts"],
  "exchange_list_distribution_groups": ["List distribution groups"],
  "exchange_list_dynamic_distribution_groups": ["Dynamic distribution groups"],
  "exchange_list_mail_contacts": ["List mail contacts"],
  "exchange_list_mail_users": ["List mail users"],
  "exchange_list_mailbox_databases": ["Show all mailbox databases"],
  "exchange_list_mailboxes": ["Show 50 mailboxes", "List all mailboxes"],
  "exchange_list_messages": ["Show recent inbox mail"],
  "exchange_list_receive_connectors": ["Show receive connectors"],
  "exchange_list_remote_domains": ["Show remote domains"],
  "exchange_list_send_connectors": ["List send connectors"],
  "exchange_list_servers": ["List Exchange servers"],
  "exchange_list_tasks": ["List tasks"],
  "exchange_move_message": ["Move a message to another folder"],
  "exchange_new_mailbox_import_request": ["Start PST import for alice@contoso.com"],
  "exchange_new_mailbox_restore_request": ["Create mailbox restore request"],
  "exchange_remove_mailbox": ["Remove mailbox alice@contoso.com"],
  "exchange_remove_mailbox_import_request": ["Cancel mailbox import request"],
  "exchange_remove_transport_rule": ["Delete transport rule \"Block Executables\""],
  "exchange_reply_message": ["Reply to a message"],
  "exchange_restore_recoverable_items": ["Recover deleted items for alice@contoso.com"],
  "exchange_retry_queue": ["Retry queue EXCH01\\Submission"],
  "exchange_search_admin_audit_log": ["Audit log search"],
  "exchange_search_mailbox": ["Search mailbox for alice@contoso.com with \"quarantine\""],
  "exchange_search_messages": ["Search messages for invoice"],
  "exchange_send_message": ["Send an email message"],
  "exchange_set_litigation_hold": ["Put alice@contoso.com on litigation hold"],
  "exchange_set_mailbox": ["Set mailbox alice@contoso.com"],
  "exchange_set_oof": ["Enable out of office for alice@contoso.com"],
  "exchange_set_transport_rule": ["Disable transport rule Block Executables"],
  "exchange_suspend_queue": ["Suspend queue EXCH01\\Submission"],
  "exchange_test_connection": ["Connectivity test"],
  "exchange_test_mailflow": ["Test mail flow"],
  "exchange_test_replication_health": ["Test replication health"],
  "exchange_test_service_health": ["Are Exchange services running?"],
  "exchange_undo_softdeleted_mailbox": ["Restore soft-deleted mailbox"],
  "group.add_member": ["Add alice@contoso.com to group \"Sales Team\""],
  "group.new": ["Create distribution group \"Sales\""],
  "log.tail_iis_log": ["Show IIS log tail"],
  "log.tail_transport_log": ["Show transport log tail"],
  "mailbox.add_permission": ["Grant FullAccess permission on alice@contoso.com to bob@contoso.com"],
  "mailbox.get_folder_statistics": ["Folder statistics for alice@contoso.com"],
  "mailbox.get_move_request_status": ["Move request status"],
  "mailbox.new_move_request": ["Move mailbox alice@contoso.com to DB05"],
  "mailbox.remove_permission": ["Remove FullAccess for alice@contoso.com from bob@contoso.com"],
  "mailbox.set_quota": ["Set quota for alice@contoso.com to 50GB"],
  "mailflow.get_message_trace": ["Trace messages from admin@contoso.com"],
  "mailflow.get_ndr_details": ["Explain bounce 5.7.1"],
  "mailflow.get_transport_rules": ["List mailflow transport rules"],
  "mailflow.resume_queue": ["Resume queue EXCH01\\Submission"],
  "mailflow.set_receive_connector": ["Update receive connector"],
  "mailflow.set_send_connector": ["Set send connector Outbound"],
  "mailflow.test_smtp_connectivity": ["SMTP test contoso.com"],
  "migration.get_moverequest_statistics": ["Show move request progress"],
  "organization.get_config": ["Show organization configuration"],
  "organization.get_info": ["Show organization info"],
  "publicfolder.get_statistics": ["Show public folder statistics"],
  "report.ad_site_exchange_mapping": ["Show AD site mapping"],
  "report.exchange_build_compliance": ["Check build compliance"],
  "report.exchange_dependency": ["Show server dependencies"],
  "report.exchange_environment_overview": ["Environment overview"],
  "report.exchange_infrastructure_summary": ["Show infrastructure summary"],
  "report.exchange_organization_configuration": ["Show Exchange organization settings"],
  "report.exchange_server_hardware": ["Show server hardware"],
  "report.exchange_server_inventory": ["Show server inventory"],
  "report.exchange_server_os": ["Show server OS versions"],
  "report.exchange_server_uptime": ["Server uptime"],
  "report.exchange_service_status": ["Show Exchange service status"],
  "report.exchange_topology": ["Show topology"],
  "report.exchange_version_and_cu": ["What version of Exchange do I have?"],
  "report.exchange_virtualization": ["Show virtualization details"],
  "report.generate_archive_report": ["Archive mailbox report"],
  "report.generate_certificate_expiry_report": ["Show certificate expiry report"],
  "report.generate_compliance_report": ["Generate compliance report"],
  "report.generate_connector_report": ["Show connector inventory"],
  "report.generate_dag_report": ["DAG report"],
  "report.generate_database_distribution_report": ["Show database distribution"],
  "report.generate_database_growth_trend": ["Database growth trend"],
  "report.generate_domain_report": ["Show domain inventory"],
  "report.generate_forwarding_report": ["Which mailboxes have forwarding enabled"],
  "report.generate_full_summary": ["Full exchange summary"],
  "report.generate_fullaccess_audit_report": ["Which mailboxes have full access enabled"],
  "report.generate_group_hygiene_report": ["Check empty distribution groups"],
  "report.generate_health_summary": ["Generate health summary"],
  "report.generate_hold_report": ["Hold report"],
  "report.generate_inactive_mailbox_report": ["Inactive mailbox report"],
  "report.generate_mailbox_size_report": ["Mailbox size report"],
  "report.generate_mobile_device_report": ["Mobile device report"],
  "report.generate_move_request_report": ["Show all move requests"],
  "report.generate_oof_report": ["OOF report"],
  "report.generate_protocol_report": ["Show client protocol usage"],
  "report.generate_quota_pressure_report": ["Show quota pressure"],
  "report.generate_transport_queue_report": ["Transport queue report"],
  "report.generate_transport_rule_report": ["Show transport rule inventory"],
  "report.mailbox_activity": ["Show mailbox activity for alice@contoso.com"],
  "report.mailbox_activity_individual": ["Show last logon for alice@contoso.com"],
  "report.mailbox_client_access_individual": ["Client access for alice@contoso.com"],
  "report.mailbox_compliance_individual": ["Mailbox compliance for alice@contoso.com"],
  "report.mailbox_detail": ["Mailbox detail for alice@contoso.com"],
  "report.mailbox_forwarding_individual": ["Forwarding for alice@contoso.com"],
  "report.mailbox_full_config": ["Full config for devlabadmin"],
  "report.mailbox_health_individual": ["Mailbox health for alice@contoso.com"],
  "report.mailbox_permissions_individual": ["Full permission report for alice@contoso.com"],
  "report.mailbox_size_individual": ["Show mailbox size breakdown for alice@contoso.com"],
  "report.mailflow_profile": ["Analyze mail flow for alice@contoso.com"],
  "report.server_role_report": ["Show server roles"],
  "security.get_mailbox_audit_log": ["Mailbox audit for alice@contoso.com"],
  "security.get_role_group_members": ["Show role group members"],
  "server.get_disk_space": ["Disk size"],
  "server.get_event_log_errors": ["Show Exchange event log errors"],
  "server.get_info": ["Show server version and edition"],
  "server.get_performance_counters": ["Show CPU and RPC performance"],
  "server.get_services_status": ["List Exchange service states"],
  "server.get_uptime": ["Server uptime"],
  "server.list": ["List Exchange servers"],
  "server.restart_service": ["Restart service MSExchangeTransport"],
  "server.run_healthchecker": ["Run Exchange HealthChecker"],
};

// Sample prompts that trigger a tool. Curated entries above win; anything
// else resolves to [] so the Docs tab stays honest (no invented triggers).
export function examplePromptsFor(tool: string): string[] {
  return TOOL_EXAMPLE_PROMPTS[tool] ?? [];
}
